server:
  port: 9095
spring:
  application:
    name: dp-kafka-hdfs
    #default.db.url=jdbc:oracle:thin:@192.168.10.81:1521/orcl
    #default.db.username=COMP_LOSS
    #default.db.password=headfree_456
#  datasource:
##    url: jdbc:oracle:thin:@10.138.78.130:11521:jhdb
##    username: COMP_LOSS
##    password: headfree_123
#    url: jdbc:oracle:thin:@192.168.10.81:1521/orcl
#    username: COMP_LOSS
#    password: headfree_456
#    driver-class-name: oracle.jdbc.driver.OracleDriver

  mvc:
    servlet:
      path: /
  resources:
    static-locations: classpath:/public,classpath:/static
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
    scheduling:
      pool:
        size: 2


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.gzkj.kafka.dao: debug
